/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const ProjectId = IDL.Nat;
export const Scale = IDL.Variant({
  'studio' : IDL.Null,
  'blockbuster' : IDL.Null,
  'indie' : IDL.Null,
});
export const BudgetLevel = IDL.Variant({
  'low' : IDL.Null,
  'high' : IDL.Null,
  'medium' : IDL.Null,
});
export const TalentStrategy = IDL.Variant({
  'starDriven' : IDL.Null,
  'established' : IDL.Null,
  'emerging' : IDL.Null,
  'unknown' : IDL.Null,
});
export const AudienceType = IDL.Variant({
  'mainstream' : IDL.Null,
  'niche' : IDL.Null,
  'broad' : IDL.Null,
});
export const MarketingBudgetLevel = IDL.Variant({
  'low' : IDL.Null,
  'high' : IDL.Null,
  'unassigned' : IDL.Null,
  'medium' : IDL.Null,
});
export const PrimaryMarketingChannel = IDL.Variant({
  'pr' : IDL.Null,
  'influencer' : IDL.Null,
  'digitalAds' : IDL.Null,
  'festival' : IDL.Null,
  'undefined' : IDL.Null,
});
export const ReleaseModel = IDL.Variant({
  'ott' : IDL.Null,
  'hybrid' : IDL.Null,
  'theatre' : IDL.Null,
});
export const DistributionConfidence = IDL.Variant({
  'low' : IDL.Null,
  'high' : IDL.Null,
  'medium' : IDL.Null,
});
export const ProductionHealth = IDL.Variant({
  'good' : IDL.Null,
  'critical' : IDL.Null,
  'atRisk' : IDL.Null,
});
export const FilmProject = IDL.Record({
  'id' : ProjectId,
  'currentPhase' : IDL.Nat,
  'distributionConfidence' : DistributionConfidence,
  'theme' : IDL.Text,
  'title' : IDL.Text,
  'marketingBudgetLevel' : MarketingBudgetLevel,
  'primaryMarketingChannel' : PrimaryMarketingChannel,
  'lastUpdated' : IDL.Int,
  'actualShootDays' : IDL.Opt(IDL.Int),
  'budgetLevel' : BudgetLevel,
  'scale' : Scale,
  'language' : IDL.Text,
  'productionHealth' : ProductionHealth,
  'talentStrategy' : TalentStrategy,
  'genre' : IDL.Text,
  'releaseModel' : ReleaseModel,
  'audienceType' : AudienceType,
  'plannedShootDays' : IDL.Int,
});
export const Insight = IDL.Record({
  'content' : IDL.Text,
  'timestamp' : IDL.Int,
});

export const idlService = IDL.Service({
  'addProjectInsight' : IDL.Func([ProjectId, IDL.Text], [], []),
  'createFilmProject' : IDL.Func(
      [
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        Scale,
        BudgetLevel,
        TalentStrategy,
        IDL.Int,
        AudienceType,
        MarketingBudgetLevel,
        PrimaryMarketingChannel,
        ReleaseModel,
        DistributionConfidence,
      ],
      [ProjectId],
      [],
    ),
  'didRuntimeTrap' : IDL.Func([], [IDL.Bool], ['query']),
  'getAllFilmProjects' : IDL.Func([], [IDL.Vec(FilmProject)], ['query']),
  'getFilmProject' : IDL.Func([ProjectId], [IDL.Opt(FilmProject)], ['query']),
  'getFilmProjectWithInsights' : IDL.Func(
      [ProjectId],
      [FilmProject, IDL.Vec(Insight)],
      ['query'],
    ),
  'getMaxProjectId' : IDL.Func([], [IDL.Nat], ['query']),
  'getProjectInsights' : IDL.Func([ProjectId], [IDL.Vec(Insight)], ['query']),
  'getProjectTitlesStartingWith' : IDL.Func(
      [IDL.Text],
      [IDL.Vec(IDL.Text)],
      ['query'],
    ),
  'updateFilmProject' : IDL.Func(
      [
        ProjectId,
        IDL.Text,
        IDL.Int,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        Scale,
        BudgetLevel,
        TalentStrategy,
        IDL.Int,
        IDL.Int,
        ProductionHealth,
        AudienceType,
        MarketingBudgetLevel,
        PrimaryMarketingChannel,
        ReleaseModel,
        DistributionConfidence,
      ],
      [],
      [],
    ),
  'updateFilmProjectPhase' : IDL.Func([ProjectId, IDL.Nat], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const ProjectId = IDL.Nat;
  const Scale = IDL.Variant({
    'studio' : IDL.Null,
    'blockbuster' : IDL.Null,
    'indie' : IDL.Null,
  });
  const BudgetLevel = IDL.Variant({
    'low' : IDL.Null,
    'high' : IDL.Null,
    'medium' : IDL.Null,
  });
  const TalentStrategy = IDL.Variant({
    'starDriven' : IDL.Null,
    'established' : IDL.Null,
    'emerging' : IDL.Null,
    'unknown' : IDL.Null,
  });
  const AudienceType = IDL.Variant({
    'mainstream' : IDL.Null,
    'niche' : IDL.Null,
    'broad' : IDL.Null,
  });
  const MarketingBudgetLevel = IDL.Variant({
    'low' : IDL.Null,
    'high' : IDL.Null,
    'unassigned' : IDL.Null,
    'medium' : IDL.Null,
  });
  const PrimaryMarketingChannel = IDL.Variant({
    'pr' : IDL.Null,
    'influencer' : IDL.Null,
    'digitalAds' : IDL.Null,
    'festival' : IDL.Null,
    'undefined' : IDL.Null,
  });
  const ReleaseModel = IDL.Variant({
    'ott' : IDL.Null,
    'hybrid' : IDL.Null,
    'theatre' : IDL.Null,
  });
  const DistributionConfidence = IDL.Variant({
    'low' : IDL.Null,
    'high' : IDL.Null,
    'medium' : IDL.Null,
  });
  const ProductionHealth = IDL.Variant({
    'good' : IDL.Null,
    'critical' : IDL.Null,
    'atRisk' : IDL.Null,
  });
  const FilmProject = IDL.Record({
    'id' : ProjectId,
    'currentPhase' : IDL.Nat,
    'distributionConfidence' : DistributionConfidence,
    'theme' : IDL.Text,
    'title' : IDL.Text,
    'marketingBudgetLevel' : MarketingBudgetLevel,
    'primaryMarketingChannel' : PrimaryMarketingChannel,
    'lastUpdated' : IDL.Int,
    'actualShootDays' : IDL.Opt(IDL.Int),
    'budgetLevel' : BudgetLevel,
    'scale' : Scale,
    'language' : IDL.Text,
    'productionHealth' : ProductionHealth,
    'talentStrategy' : TalentStrategy,
    'genre' : IDL.Text,
    'releaseModel' : ReleaseModel,
    'audienceType' : AudienceType,
    'plannedShootDays' : IDL.Int,
  });
  const Insight = IDL.Record({ 'content' : IDL.Text, 'timestamp' : IDL.Int });
  
  return IDL.Service({
    'addProjectInsight' : IDL.Func([ProjectId, IDL.Text], [], []),
    'createFilmProject' : IDL.Func(
        [
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          Scale,
          BudgetLevel,
          TalentStrategy,
          IDL.Int,
          AudienceType,
          MarketingBudgetLevel,
          PrimaryMarketingChannel,
          ReleaseModel,
          DistributionConfidence,
        ],
        [ProjectId],
        [],
      ),
    'didRuntimeTrap' : IDL.Func([], [IDL.Bool], ['query']),
    'getAllFilmProjects' : IDL.Func([], [IDL.Vec(FilmProject)], ['query']),
    'getFilmProject' : IDL.Func([ProjectId], [IDL.Opt(FilmProject)], ['query']),
    'getFilmProjectWithInsights' : IDL.Func(
        [ProjectId],
        [FilmProject, IDL.Vec(Insight)],
        ['query'],
      ),
    'getMaxProjectId' : IDL.Func([], [IDL.Nat], ['query']),
    'getProjectInsights' : IDL.Func([ProjectId], [IDL.Vec(Insight)], ['query']),
    'getProjectTitlesStartingWith' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(IDL.Text)],
        ['query'],
      ),
    'updateFilmProject' : IDL.Func(
        [
          ProjectId,
          IDL.Text,
          IDL.Int,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          Scale,
          BudgetLevel,
          TalentStrategy,
          IDL.Int,
          IDL.Int,
          ProductionHealth,
          AudienceType,
          MarketingBudgetLevel,
          PrimaryMarketingChannel,
          ReleaseModel,
          DistributionConfidence,
        ],
        [],
        [],
      ),
    'updateFilmProjectPhase' : IDL.Func([ProjectId, IDL.Nat], [], []),
  });
};

export const init = ({ IDL }) => { return []; };