/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export type AudienceType = { 'mainstream' : null } |
  { 'niche' : null } |
  { 'broad' : null };
export type BudgetLevel = { 'low' : null } |
  { 'high' : null } |
  { 'medium' : null };
export type DistributionConfidence = { 'low' : null } |
  { 'high' : null } |
  { 'medium' : null };
export interface FilmProject {
  'id' : ProjectId,
  'currentPhase' : bigint,
  'distributionConfidence' : DistributionConfidence,
  'theme' : string,
  'title' : string,
  'marketingBudgetLevel' : MarketingBudgetLevel,
  'primaryMarketingChannel' : PrimaryMarketingChannel,
  'lastUpdated' : bigint,
  'actualShootDays' : [] | [bigint],
  'budgetLevel' : BudgetLevel,
  'scale' : Scale,
  'language' : string,
  'productionHealth' : ProductionHealth,
  'talentStrategy' : TalentStrategy,
  'genre' : string,
  'releaseModel' : ReleaseModel,
  'audienceType' : AudienceType,
  'plannedShootDays' : bigint,
}
export interface Insight { 'content' : string, 'timestamp' : bigint }
export type MarketingBudgetLevel = { 'low' : null } |
  { 'high' : null } |
  { 'unassigned' : null } |
  { 'medium' : null };
export type PrimaryMarketingChannel = { 'pr' : null } |
  { 'influencer' : null } |
  { 'digitalAds' : null } |
  { 'festival' : null } |
  { 'undefined' : null };
export type ProductionHealth = { 'good' : null } |
  { 'critical' : null } |
  { 'atRisk' : null };
export type ProjectId = bigint;
export type ReleaseModel = { 'ott' : null } |
  { 'hybrid' : null } |
  { 'theatre' : null };
export type Scale = { 'studio' : null } |
  { 'blockbuster' : null } |
  { 'indie' : null };
export type TalentStrategy = { 'starDriven' : null } |
  { 'established' : null } |
  { 'emerging' : null } |
  { 'unknown' : null };
export interface _SERVICE {
  'addProjectInsight' : ActorMethod<[ProjectId, string], undefined>,
  'createFilmProject' : ActorMethod<
    [
      string,
      string,
      string,
      string,
      Scale,
      BudgetLevel,
      TalentStrategy,
      bigint,
      AudienceType,
      MarketingBudgetLevel,
      PrimaryMarketingChannel,
      ReleaseModel,
      DistributionConfidence,
    ],
    ProjectId
  >,
  'didRuntimeTrap' : ActorMethod<[], boolean>,
  'getAllFilmProjects' : ActorMethod<[], Array<FilmProject>>,
  'getFilmProject' : ActorMethod<[ProjectId], [] | [FilmProject]>,
  'getFilmProjectWithInsights' : ActorMethod<
    [ProjectId],
    [FilmProject, Array<Insight>]
  >,
  'getMaxProjectId' : ActorMethod<[], bigint>,
  'getProjectInsights' : ActorMethod<[ProjectId], Array<Insight>>,
  'getProjectTitlesStartingWith' : ActorMethod<[string], Array<string>>,
  'updateFilmProject' : ActorMethod<
    [
      ProjectId,
      string,
      bigint,
      string,
      string,
      string,
      Scale,
      BudgetLevel,
      TalentStrategy,
      bigint,
      bigint,
      ProductionHealth,
      AudienceType,
      MarketingBudgetLevel,
      PrimaryMarketingChannel,
      ReleaseModel,
      DistributionConfidence,
    ],
    undefined
  >,
  'updateFilmProjectPhase' : ActorMethod<[ProjectId, bigint], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];