/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface Insight {
    content: string;
    timestamp: bigint;
}
export interface FilmProject {
    id: ProjectId;
    currentPhase: bigint;
    distributionConfidence: DistributionConfidence;
    theme: string;
    title: string;
    marketingBudgetLevel: MarketingBudgetLevel;
    primaryMarketingChannel: PrimaryMarketingChannel;
    lastUpdated: bigint;
    actualShootDays?: bigint;
    budgetLevel: BudgetLevel;
    scale: Scale;
    language: string;
    productionHealth: ProductionHealth;
    talentStrategy: TalentStrategy;
    genre: string;
    releaseModel: ReleaseModel;
    audienceType: AudienceType;
    plannedShootDays: bigint;
}
export type ProjectId = bigint;
export enum AudienceType {
    mainstream = "mainstream",
    niche = "niche",
    broad = "broad"
}
export enum DistributionConfidence {
    low = "low",
    high = "high",
    medium = "medium"
}
export enum MarketingBudgetLevel {
    low = "low",
    high = "high",
    unassigned = "unassigned",
    medium = "medium"
}
export enum PrimaryMarketingChannel {
    pr = "pr",
    influencer = "influencer",
    digitalAds = "digitalAds",
    festival = "festival",
    undefined_ = "undefined"
}
export enum ProductionHealth {
    good = "good",
    critical = "critical",
    atRisk = "atRisk"
}
export enum ReleaseModel {
    ott = "ott",
    hybrid = "hybrid",
    theatre = "theatre"
}
export enum Scale {
    studio = "studio",
    blockbuster = "blockbuster",
    indie = "indie"
}
export enum TalentStrategy {
    starDriven = "starDriven",
    established = "established",
    emerging = "emerging",
    unknown_ = "unknown"
}
export interface backendInterface {
    addProjectInsight(projectId: ProjectId, content: string): Promise<void>;
    createFilmProject(title: string, genre: string, language: string, theme: string, scale: Scale, budgetLevel: BudgetLevel, talentStrategy: TalentStrategy, plannedShootDays: bigint, audienceType: AudienceType, marketingBudgetLevel: MarketingBudgetLevel, primaryMarketingChannel: PrimaryMarketingChannel, releaseModel: ReleaseModel, distributionConfidence: DistributionConfidence): Promise<ProjectId>;
    didRuntimeTrap(): Promise<boolean>;
    getAllFilmProjects(): Promise<Array<FilmProject>>;
    getFilmProject(projectId: ProjectId): Promise<FilmProject | null>;
    getFilmProjectWithInsights(projectId: ProjectId): Promise<[FilmProject, Array<Insight>]>;
    getMaxProjectId(): Promise<bigint>;
    getProjectInsights(projectId: ProjectId): Promise<Array<Insight>>;
    getProjectTitlesStartingWith(letter: string): Promise<Array<string>>;
    updateFilmProject(projectId: ProjectId, title: string, phase: bigint, genre: string, language: string, theme: string, scale: Scale, budgetLevel: BudgetLevel, talentStrategy: TalentStrategy, plannedShootDays: bigint, actualShootDays: bigint, productionHealth: ProductionHealth, audienceType: AudienceType, marketingBudgetLevel: MarketingBudgetLevel, primaryMarketingChannel: PrimaryMarketingChannel, releaseModel: ReleaseModel, distributionConfidence: DistributionConfidence): Promise<void>;
    updateFilmProjectPhase(projectId: ProjectId, newPhase: bigint): Promise<void>;
}
import type { AudienceType as _AudienceType, BudgetLevel as _BudgetLevel, DistributionConfidence as _DistributionConfidence, FilmProject as _FilmProject, MarketingBudgetLevel as _MarketingBudgetLevel, PrimaryMarketingChannel as _PrimaryMarketingChannel, ProductionHealth as _ProductionHealth, ProjectId as _ProjectId, ReleaseModel as _ReleaseModel, Scale as _Scale, TalentStrategy as _TalentStrategy } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async addProjectInsight(arg0: ProjectId, arg1: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.addProjectInsight(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addProjectInsight(arg0, arg1);
            return result;
        }
    }
    async createFilmProject(arg0: string, arg1: string, arg2: string, arg3: string, arg4: Scale, arg5: BudgetLevel, arg6: TalentStrategy, arg7: bigint, arg8: AudienceType, arg9: MarketingBudgetLevel, arg10: PrimaryMarketingChannel, arg11: ReleaseModel, arg12: DistributionConfidence): Promise<ProjectId> {
        if (this.processError) {
            try {
                const result = await this.actor.createFilmProject(arg0, arg1, arg2, arg3, to_candid_Scale_n1(this._uploadFile, this._downloadFile, arg4), to_candid_BudgetLevel_n3(this._uploadFile, this._downloadFile, arg5), to_candid_TalentStrategy_n5(this._uploadFile, this._downloadFile, arg6), arg7, to_candid_AudienceType_n7(this._uploadFile, this._downloadFile, arg8), to_candid_MarketingBudgetLevel_n9(this._uploadFile, this._downloadFile, arg9), to_candid_PrimaryMarketingChannel_n11(this._uploadFile, this._downloadFile, arg10), to_candid_ReleaseModel_n13(this._uploadFile, this._downloadFile, arg11), to_candid_DistributionConfidence_n15(this._uploadFile, this._downloadFile, arg12));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createFilmProject(arg0, arg1, arg2, arg3, to_candid_Scale_n1(this._uploadFile, this._downloadFile, arg4), to_candid_BudgetLevel_n3(this._uploadFile, this._downloadFile, arg5), to_candid_TalentStrategy_n5(this._uploadFile, this._downloadFile, arg6), arg7, to_candid_AudienceType_n7(this._uploadFile, this._downloadFile, arg8), to_candid_MarketingBudgetLevel_n9(this._uploadFile, this._downloadFile, arg9), to_candid_PrimaryMarketingChannel_n11(this._uploadFile, this._downloadFile, arg10), to_candid_ReleaseModel_n13(this._uploadFile, this._downloadFile, arg11), to_candid_DistributionConfidence_n15(this._uploadFile, this._downloadFile, arg12));
            return result;
        }
    }
    async didRuntimeTrap(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.didRuntimeTrap();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.didRuntimeTrap();
            return result;
        }
    }
    async getAllFilmProjects(): Promise<Array<FilmProject>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllFilmProjects();
                return from_candid_vec_n16(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllFilmProjects();
            return from_candid_vec_n16(this._uploadFile, this._downloadFile, result);
        }
    }
    async getFilmProject(arg0: ProjectId): Promise<FilmProject | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getFilmProject(arg0);
                return from_candid_opt_n37(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getFilmProject(arg0);
            return from_candid_opt_n37(this._uploadFile, this._downloadFile, result);
        }
    }
    async getFilmProjectWithInsights(arg0: ProjectId): Promise<[FilmProject, Array<Insight>]> {
        if (this.processError) {
            try {
                const result = await this.actor.getFilmProjectWithInsights(arg0);
                return [
                    from_candid_FilmProject_n17(this._uploadFile, this._downloadFile, result[0]),
                    result[1]
                ];
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getFilmProjectWithInsights(arg0);
            return [
                from_candid_FilmProject_n17(this._uploadFile, this._downloadFile, result[0]),
                result[1]
            ];
        }
    }
    async getMaxProjectId(): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.getMaxProjectId();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getMaxProjectId();
            return result;
        }
    }
    async getProjectInsights(arg0: ProjectId): Promise<Array<Insight>> {
        if (this.processError) {
            try {
                const result = await this.actor.getProjectInsights(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getProjectInsights(arg0);
            return result;
        }
    }
    async getProjectTitlesStartingWith(arg0: string): Promise<Array<string>> {
        if (this.processError) {
            try {
                const result = await this.actor.getProjectTitlesStartingWith(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getProjectTitlesStartingWith(arg0);
            return result;
        }
    }
    async updateFilmProject(arg0: ProjectId, arg1: string, arg2: bigint, arg3: string, arg4: string, arg5: string, arg6: Scale, arg7: BudgetLevel, arg8: TalentStrategy, arg9: bigint, arg10: bigint, arg11: ProductionHealth, arg12: AudienceType, arg13: MarketingBudgetLevel, arg14: PrimaryMarketingChannel, arg15: ReleaseModel, arg16: DistributionConfidence): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateFilmProject(arg0, arg1, arg2, arg3, arg4, arg5, to_candid_Scale_n1(this._uploadFile, this._downloadFile, arg6), to_candid_BudgetLevel_n3(this._uploadFile, this._downloadFile, arg7), to_candid_TalentStrategy_n5(this._uploadFile, this._downloadFile, arg8), arg9, arg10, to_candid_ProductionHealth_n38(this._uploadFile, this._downloadFile, arg11), to_candid_AudienceType_n7(this._uploadFile, this._downloadFile, arg12), to_candid_MarketingBudgetLevel_n9(this._uploadFile, this._downloadFile, arg13), to_candid_PrimaryMarketingChannel_n11(this._uploadFile, this._downloadFile, arg14), to_candid_ReleaseModel_n13(this._uploadFile, this._downloadFile, arg15), to_candid_DistributionConfidence_n15(this._uploadFile, this._downloadFile, arg16));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateFilmProject(arg0, arg1, arg2, arg3, arg4, arg5, to_candid_Scale_n1(this._uploadFile, this._downloadFile, arg6), to_candid_BudgetLevel_n3(this._uploadFile, this._downloadFile, arg7), to_candid_TalentStrategy_n5(this._uploadFile, this._downloadFile, arg8), arg9, arg10, to_candid_ProductionHealth_n38(this._uploadFile, this._downloadFile, arg11), to_candid_AudienceType_n7(this._uploadFile, this._downloadFile, arg12), to_candid_MarketingBudgetLevel_n9(this._uploadFile, this._downloadFile, arg13), to_candid_PrimaryMarketingChannel_n11(this._uploadFile, this._downloadFile, arg14), to_candid_ReleaseModel_n13(this._uploadFile, this._downloadFile, arg15), to_candid_DistributionConfidence_n15(this._uploadFile, this._downloadFile, arg16));
            return result;
        }
    }
    async updateFilmProjectPhase(arg0: ProjectId, arg1: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateFilmProjectPhase(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateFilmProjectPhase(arg0, arg1);
            return result;
        }
    }
}
function from_candid_AudienceType_n35(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _AudienceType): AudienceType {
    return from_candid_variant_n36(_uploadFile, _downloadFile, value);
}
function from_candid_BudgetLevel_n26(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _BudgetLevel): BudgetLevel {
    return from_candid_variant_n20(_uploadFile, _downloadFile, value);
}
function from_candid_DistributionConfidence_n19(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _DistributionConfidence): DistributionConfidence {
    return from_candid_variant_n20(_uploadFile, _downloadFile, value);
}
function from_candid_FilmProject_n17(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _FilmProject): FilmProject {
    return from_candid_record_n18(_uploadFile, _downloadFile, value);
}
function from_candid_MarketingBudgetLevel_n21(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _MarketingBudgetLevel): MarketingBudgetLevel {
    return from_candid_variant_n22(_uploadFile, _downloadFile, value);
}
function from_candid_PrimaryMarketingChannel_n23(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _PrimaryMarketingChannel): PrimaryMarketingChannel {
    return from_candid_variant_n24(_uploadFile, _downloadFile, value);
}
function from_candid_ProductionHealth_n29(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ProductionHealth): ProductionHealth {
    return from_candid_variant_n30(_uploadFile, _downloadFile, value);
}
function from_candid_ReleaseModel_n33(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ReleaseModel): ReleaseModel {
    return from_candid_variant_n34(_uploadFile, _downloadFile, value);
}
function from_candid_Scale_n27(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Scale): Scale {
    return from_candid_variant_n28(_uploadFile, _downloadFile, value);
}
function from_candid_TalentStrategy_n31(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _TalentStrategy): TalentStrategy {
    return from_candid_variant_n32(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n25(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [bigint]): bigint | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n37(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_FilmProject]): FilmProject | null {
    return value.length === 0 ? null : from_candid_FilmProject_n17(_uploadFile, _downloadFile, value[0]);
}
function from_candid_record_n18(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: _ProjectId;
    currentPhase: bigint;
    distributionConfidence: _DistributionConfidence;
    theme: string;
    title: string;
    marketingBudgetLevel: _MarketingBudgetLevel;
    primaryMarketingChannel: _PrimaryMarketingChannel;
    lastUpdated: bigint;
    actualShootDays: [] | [bigint];
    budgetLevel: _BudgetLevel;
    scale: _Scale;
    language: string;
    productionHealth: _ProductionHealth;
    talentStrategy: _TalentStrategy;
    genre: string;
    releaseModel: _ReleaseModel;
    audienceType: _AudienceType;
    plannedShootDays: bigint;
}): {
    id: ProjectId;
    currentPhase: bigint;
    distributionConfidence: DistributionConfidence;
    theme: string;
    title: string;
    marketingBudgetLevel: MarketingBudgetLevel;
    primaryMarketingChannel: PrimaryMarketingChannel;
    lastUpdated: bigint;
    actualShootDays?: bigint;
    budgetLevel: BudgetLevel;
    scale: Scale;
    language: string;
    productionHealth: ProductionHealth;
    talentStrategy: TalentStrategy;
    genre: string;
    releaseModel: ReleaseModel;
    audienceType: AudienceType;
    plannedShootDays: bigint;
} {
    return {
        id: value.id,
        currentPhase: value.currentPhase,
        distributionConfidence: from_candid_DistributionConfidence_n19(_uploadFile, _downloadFile, value.distributionConfidence),
        theme: value.theme,
        title: value.title,
        marketingBudgetLevel: from_candid_MarketingBudgetLevel_n21(_uploadFile, _downloadFile, value.marketingBudgetLevel),
        primaryMarketingChannel: from_candid_PrimaryMarketingChannel_n23(_uploadFile, _downloadFile, value.primaryMarketingChannel),
        lastUpdated: value.lastUpdated,
        actualShootDays: record_opt_to_undefined(from_candid_opt_n25(_uploadFile, _downloadFile, value.actualShootDays)),
        budgetLevel: from_candid_BudgetLevel_n26(_uploadFile, _downloadFile, value.budgetLevel),
        scale: from_candid_Scale_n27(_uploadFile, _downloadFile, value.scale),
        language: value.language,
        productionHealth: from_candid_ProductionHealth_n29(_uploadFile, _downloadFile, value.productionHealth),
        talentStrategy: from_candid_TalentStrategy_n31(_uploadFile, _downloadFile, value.talentStrategy),
        genre: value.genre,
        releaseModel: from_candid_ReleaseModel_n33(_uploadFile, _downloadFile, value.releaseModel),
        audienceType: from_candid_AudienceType_n35(_uploadFile, _downloadFile, value.audienceType),
        plannedShootDays: value.plannedShootDays
    };
}
function from_candid_variant_n20(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    low: null;
} | {
    high: null;
} | {
    medium: null;
}): DistributionConfidence {
    return "low" in value ? DistributionConfidence.low : "high" in value ? DistributionConfidence.high : "medium" in value ? DistributionConfidence.medium : value;
}
function from_candid_variant_n22(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    low: null;
} | {
    high: null;
} | {
    unassigned: null;
} | {
    medium: null;
}): MarketingBudgetLevel {
    return "low" in value ? MarketingBudgetLevel.low : "high" in value ? MarketingBudgetLevel.high : "unassigned" in value ? MarketingBudgetLevel.unassigned : "medium" in value ? MarketingBudgetLevel.medium : value;
}
function from_candid_variant_n24(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    pr: null;
} | {
    influencer: null;
} | {
    digitalAds: null;
} | {
    festival: null;
} | {
    undefined: null;
}): PrimaryMarketingChannel {
    return "pr" in value ? PrimaryMarketingChannel.pr : "influencer" in value ? PrimaryMarketingChannel.influencer : "digitalAds" in value ? PrimaryMarketingChannel.digitalAds : "festival" in value ? PrimaryMarketingChannel.festival : "undefined" in value ? PrimaryMarketingChannel.undefined : value;
}
function from_candid_variant_n28(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    studio: null;
} | {
    blockbuster: null;
} | {
    indie: null;
}): Scale {
    return "studio" in value ? Scale.studio : "blockbuster" in value ? Scale.blockbuster : "indie" in value ? Scale.indie : value;
}
function from_candid_variant_n30(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    good: null;
} | {
    critical: null;
} | {
    atRisk: null;
}): ProductionHealth {
    return "good" in value ? ProductionHealth.good : "critical" in value ? ProductionHealth.critical : "atRisk" in value ? ProductionHealth.atRisk : value;
}
function from_candid_variant_n32(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    starDriven: null;
} | {
    established: null;
} | {
    emerging: null;
} | {
    unknown: null;
}): TalentStrategy {
    return "starDriven" in value ? TalentStrategy.starDriven : "established" in value ? TalentStrategy.established : "emerging" in value ? TalentStrategy.emerging : "unknown" in value ? TalentStrategy.unknown : value;
}
function from_candid_variant_n34(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    ott: null;
} | {
    hybrid: null;
} | {
    theatre: null;
}): ReleaseModel {
    return "ott" in value ? ReleaseModel.ott : "hybrid" in value ? ReleaseModel.hybrid : "theatre" in value ? ReleaseModel.theatre : value;
}
function from_candid_variant_n36(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    mainstream: null;
} | {
    niche: null;
} | {
    broad: null;
}): AudienceType {
    return "mainstream" in value ? AudienceType.mainstream : "niche" in value ? AudienceType.niche : "broad" in value ? AudienceType.broad : value;
}
function from_candid_vec_n16(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_FilmProject>): Array<FilmProject> {
    return value.map((x)=>from_candid_FilmProject_n17(_uploadFile, _downloadFile, x));
}
function to_candid_AudienceType_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: AudienceType): _AudienceType {
    return to_candid_variant_n8(_uploadFile, _downloadFile, value);
}
function to_candid_BudgetLevel_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: BudgetLevel): _BudgetLevel {
    return to_candid_variant_n4(_uploadFile, _downloadFile, value);
}
function to_candid_DistributionConfidence_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: DistributionConfidence): _DistributionConfidence {
    return to_candid_variant_n4(_uploadFile, _downloadFile, value);
}
function to_candid_MarketingBudgetLevel_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: MarketingBudgetLevel): _MarketingBudgetLevel {
    return to_candid_variant_n10(_uploadFile, _downloadFile, value);
}
function to_candid_PrimaryMarketingChannel_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: PrimaryMarketingChannel): _PrimaryMarketingChannel {
    return to_candid_variant_n12(_uploadFile, _downloadFile, value);
}
function to_candid_ProductionHealth_n38(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ProductionHealth): _ProductionHealth {
    return to_candid_variant_n39(_uploadFile, _downloadFile, value);
}
function to_candid_ReleaseModel_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ReleaseModel): _ReleaseModel {
    return to_candid_variant_n14(_uploadFile, _downloadFile, value);
}
function to_candid_Scale_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Scale): _Scale {
    return to_candid_variant_n2(_uploadFile, _downloadFile, value);
}
function to_candid_TalentStrategy_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: TalentStrategy): _TalentStrategy {
    return to_candid_variant_n6(_uploadFile, _downloadFile, value);
}
function to_candid_variant_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: MarketingBudgetLevel): {
    low: null;
} | {
    high: null;
} | {
    unassigned: null;
} | {
    medium: null;
} {
    return value == MarketingBudgetLevel.low ? {
        low: null
    } : value == MarketingBudgetLevel.high ? {
        high: null
    } : value == MarketingBudgetLevel.unassigned ? {
        unassigned: null
    } : value == MarketingBudgetLevel.medium ? {
        medium: null
    } : value;
}
function to_candid_variant_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: PrimaryMarketingChannel): {
    pr: null;
} | {
    influencer: null;
} | {
    digitalAds: null;
} | {
    festival: null;
} | {
    undefined: null;
} {
    return value == PrimaryMarketingChannel.pr ? {
        pr: null
    } : value == PrimaryMarketingChannel.influencer ? {
        influencer: null
    } : value == PrimaryMarketingChannel.digitalAds ? {
        digitalAds: null
    } : value == PrimaryMarketingChannel.festival ? {
        festival: null
    } : value == PrimaryMarketingChannel.undefined ? {
        undefined_: null
    } : value;
}
function to_candid_variant_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ReleaseModel): {
    ott: null;
} | {
    hybrid: null;
} | {
    theatre: null;
} {
    return value == ReleaseModel.ott ? {
        ott: null
    } : value == ReleaseModel.hybrid ? {
        hybrid: null
    } : value == ReleaseModel.theatre ? {
        theatre: null
    } : value;
}
function to_candid_variant_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Scale): {
    studio: null;
} | {
    blockbuster: null;
} | {
    indie: null;
} {
    return value == Scale.studio ? {
        studio: null
    } : value == Scale.blockbuster ? {
        blockbuster: null
    } : value == Scale.indie ? {
        indie: null
    } : value;
}
function to_candid_variant_n39(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ProductionHealth): {
    good: null;
} | {
    critical: null;
} | {
    atRisk: null;
} {
    return value == ProductionHealth.good ? {
        good: null
    } : value == ProductionHealth.critical ? {
        critical: null
    } : value == ProductionHealth.atRisk ? {
        atRisk: null
    } : value;
}
function to_candid_variant_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: DistributionConfidence): {
    low: null;
} | {
    high: null;
} | {
    medium: null;
} {
    return value == DistributionConfidence.low ? {
        low: null
    } : value == DistributionConfidence.high ? {
        high: null
    } : value == DistributionConfidence.medium ? {
        medium: null
    } : value;
}
function to_candid_variant_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: TalentStrategy): {
    starDriven: null;
} | {
    established: null;
} | {
    emerging: null;
} | {
    unknown: null;
} {
    return value == TalentStrategy.starDriven ? {
        starDriven: null
    } : value == TalentStrategy.established ? {
        established: null
    } : value == TalentStrategy.emerging ? {
        emerging: null
    } : value == TalentStrategy.unknown ? {
        unknown_: null
    } : value;
}
function to_candid_variant_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: AudienceType): {
    mainstream: null;
} | {
    niche: null;
} | {
    broad: null;
} {
    return value == AudienceType.mainstream ? {
        mainstream: null
    } : value == AudienceType.niche ? {
        niche: null
    } : value == AudienceType.broad ? {
        broad: null
    } : value;
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
